package com.community.cms.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import java.time.LocalDateTime;

/**
 * Represents a translation of a page content for a specific language.
 * Contains localized versions of page title, content and SEO metadata.
 * Представляет перевод содержимого страницы для конкретного языка.
 * Содержит локализованные версии заголовка страницы, содержимого и SEO метаданных.
 *
 * @author Vasickin
 * @version 1.0
 * @since 2024
 * @see Page
 * @see Language
 */
@Entity
@Table(name = "page_translations", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"page_id", "language"})
})
public class PageTranslation {

    /**
     * Unique identifier for the page translation.
     * Automatically generated by the database.
     * Уникальный идентификатор перевода страницы.
     * Автоматически генерируется базой данных.
     *
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The parent page entity that this translation belongs to.
     * Many translations can belong to one page.
     * Uses lazy fetching for performance optimization.
     * Родительская сущность страницы, к которой принадлежит этот перевод.
     * Многие переводы могут принадлежать одной странице.
     * Использует ленивую загрузку для оптимизации производительности.
     *
     * @see Page
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "page_id", nullable = false, foreignKey = @ForeignKey(name = "fk_page_translation_page"))
    private Page page;

    /**
     * The language of this translation.
     * Defines which language version this entity represents.
     * Stored as string enum values (RU, LT, EN).
     * Язык данного перевода.
     * Определяет, какую языковую версию представляет эта сущность.
     * Хранится в виде строковых значений перечисления (RU, LT, EN).
     *
     * @see Language
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 2)
    private Language language;

    /**
     * The localized title of the page in the specified language.
     * This field is required and cannot be blank.
     * Локализованный заголовок страницы на указанном языке.
     * Это поле является обязательным и не может быть пустым.
     *
     */
    @NotBlank(message = "Title is required for page translation")
    @Column(nullable = false, length = 500)
    private String title;

    /**
     * The localized content of the page in the specified language.
     * Can contain HTML markup for rich text formatting.
     * Stored as TEXT to support large content.
     * Локализованное содержимое страницы на указанном языке.
     * Может содержать HTML разметку для форматирования текста.
     * Хранится как TEXT для поддержки большого объема содержимого.
     *
     */
    @Column(columnDefinition = "TEXT")
    private String content;

    /**
     * Custom meta title for SEO optimization.
     * If not provided, the regular title will be used for SEO.
     * Пользовательский мета-заголовок для SEO оптимизации.
     * Если не указан, для SEO будет использоваться обычный заголовок.
     *
     */
    @Column(name = "meta_title", length = 500)
    private String metaTitle;

    /**
     * Custom meta description for SEO optimization.
     * Provides a brief summary of the page content for search engines.
     * Пользовательское мета-описание для SEO оптимизации.
     * Предоставляет краткое описание содержимого страницы для поисковых систем.
     *
     */
    @Column(name = "meta_description", length = 1000)
    private String metaDescription;

    /**
     * Timestamp when this translation was created.
     * Automatically set when the entity is first persisted.
     * Отметка времени, когда этот перевод был создан.
     * Автоматически устанавливается при первом сохранении сущности.
     *
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this translation was last updated.
     * Automatically updated when the entity is modified.
     * Отметка времени, когда этот перевод был последний раз обновлен.
     * Автоматически обновляется при изменении сущности.
     *
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Default constructor for JPA.
     * Конструктор по умолчанию для JPA.
     */
    public PageTranslation() {
        // Default constructor for JPA
    }

    /**
     * Constructor with required fields for creating a new page translation.
     * Конструктор с обязательными полями для создания нового перевода страницы.
     *
     * @param page the parent page entity / родительская сущность страницы
     * @param language the language of this translation / язык данного перевода
     * @param title the localized title / локализованный заголовок
     * @param content the localized content / локализованное содержимое
     */
    public PageTranslation(Page page, Language language, String title, String content) {
        this.page = page;
        this.language = language;
        this.title = title;
        this.content = content;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    // Getters and setters with JavaDoc comments...

    /**
     * Gets the unique identifier of this translation.
     * Получает уникальный идентификатор этого перевода.
     *
     * @return the translation ID / идентификатор перевода
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of this translation.
     * Note: This is typically set automatically by JPA.
     * Устанавливает уникальный идентификатор этого перевода.
     * Примечание: Обычно устанавливается автоматически JPA.
     *
     * @param id the translation ID / идентификатор перевода
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the parent page entity.
     * Получает родительскую сущность страницы.
     *
     * @return the parent page / родительская страница
     */
    public Page getPage() {
        return page;
    }

    /**
     * Sets the parent page entity.
     * Устанавливает родительскую сущность страницы.
     *
     * @param page the parent page / родительская страница
     */
    public void setPage(Page page) {
        this.page = page;
    }

    /**
     * Gets the language of this translation.
     * Получает язык этого перевода.
     *
     * @return the language / язык
     */
    public Language getLanguage() {
        return language;
    }

    /**
     * Sets the language of this translation.
     * Устанавливает язык этого перевода.
     *
     * @param language the language / язык
     */
    public void setLanguage(Language language) {
        this.language = language;
    }

    /**
     * Gets the localized title.
     * Получает локализованный заголовок.
     *
     * @return the title / заголовок
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the localized title.
     * Устанавливает локализованный заголовок.
     *
     * @param title the title / заголовок
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Gets the localized content.
     * Получает локализованное содержимое.
     *
     * @return the content / содержимое
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the localized content.
     * Устанавливает локализованное содержимое.
     *
     * @param content the content / содержимое
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Gets the custom meta title for SEO.
     * Получает пользовательский мета-заголовок для SEO.
     *
     * @return the meta title / мета-заголовок
     */
    public String getMetaTitle() {
        return metaTitle;
    }

    /**
     * Sets the custom meta title for SEO.
     * Устанавливает пользовательский мета-заголовок для SEO.
     *
     * @param metaTitle the meta title / мета-заголовок
     */
    public void setMetaTitle(String metaTitle) {
        this.metaTitle = metaTitle;
    }

    /**
     * Gets the custom meta description for SEO.
     * Получает пользовательское мета-описание для SEO.
     *
     * @return the meta description / мета-описание
     */
    public String getMetaDescription() {
        return metaDescription;
    }

    /**
     * Sets the custom meta description for SEO.
     * Устанавливает пользовательское мета-описание для SEO.
     *
     * @param metaDescription the meta description / мета-описание
     */
    public void setMetaDescription(String metaDescription) {
        this.metaDescription = metaDescription;
    }

    /**
     * Gets the creation timestamp.
     * Получает отметку времени создания.
     *
     * @return the creation timestamp / отметка времени создания
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp.
     * Typically called automatically before entity persistence.
     * Устанавливает отметку времени создания.
     * Обычно вызывается автоматически перед сохранением сущности.
     *
     * @param createdAt the creation timestamp / отметка времени создания
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets the last update timestamp.
     * Получает отметку времени последнего обновления.
     *
     * @return the update timestamp / отметка времени обновления
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the last update timestamp.
     * Typically called automatically before entity update.
     * Устанавливает отметку времени последнего обновления.
     * Обычно вызывается автоматически перед обновлением сущности.
     *
     * @param updatedAt the update timestamp / отметка времени обновления
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Returns a string representation of the page translation.
     * Includes ID, language and title for debugging purposes.
     * Возвращает строковое представление перевода страницы.
     * Включает ID, язык и заголовок для целей отладки.
     *
     * @return string representation of the translation / строковое представление перевода
     */
    @Override
    public String toString() {
        return "PageTranslation{" +
                "id=" + id +
                ", language=" + language +
                ", title='" + title + '\'' +
                '}';
    }
}
