package com.community.cms.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Represents a page in the CMS system with multilingual support.
 * Each page can have multiple translations for different languages.
 * The page itself contains structural information while translations hold localized content.
 * Представляет страницу в системе CMS с поддержкой многозадачности.
 * Каждая страница может иметь несколько переводов для разных языков.
 * Сама страница содержит структурную информацию, а переводы содержат локализованный контент.
 *
 * @author Vasickin
 * @version 2.0
 * @since 2024
 * @see PageTranslation
 * @see Language
 */
@Entity
@Table(name = "pages")
public class Page {

    /**
     * Unique identifier for the page.
     * Automatically generated by the database.
     * Уникальный идентификатор страницы.
     * Автоматически генерируется базой данных.
     *
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique URL slug for the page.
     * Used in URLs to identify the page (e.g., "about-us", "contacts").
     * Must be unique across all pages.
     * Уникальный URL-идентификатор для страницы.
     * Используется в URL для идентификации страницы (например, "about-us", "contacts").
     * Должен быть уникальным для всех страниц.
     *
     */
    @NotBlank(message = "URL slug is required")
    @Column(nullable = false, unique = true, length = 200)
    private String slug;

    /**
     * Collection of translations for this page.
     * Each translation represents the page content in a specific language.
     * Uses cascade operations to manage translations lifecycle with the page.
     * Коллекция переводов для этой страницы.
     * Каждый перевод представляет содержимое страницы на определенном языке.
     * Использует каскадные операции для управления жизненным циклом переводов вместе со страницей.
     *
     * @see PageTranslation
     */
    @OneToMany(mappedBy = "page", cascade = CascadeType.ALL, orphanRemoval = true, fetch = FetchType.LAZY)
    private List<PageTranslation> translations = new ArrayList<>();

    /**
     * Indicates whether the page is published and visible to public.
     * Unpublished pages are only accessible via admin interface.
     * Указывает, опубликована ли страница и видна ли публично.
     * Неопубликованные страницы доступны только через админ-интерфейс.
     *
     */
    @Column(name = "is_published", nullable = false)
    private Boolean isPublished = false;

    /**
     * Order of the page in navigation menus.
     * Lower numbers appear first in sorted lists.
     * Порядок страницы в навигационных меню.
     * Меньшие числа отображаются первыми в отсортированных списках.
     *
     */
    @Column(name = "sort_order")
    private Integer sortOrder = 0;

    /**
     * Timestamp when the page was created.
     * Automatically set when the page is first persisted.
     * Отметка времени, когда страница была создана.
     * Автоматически устанавливается при первом сохранении страницы.
     *
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when the page was last updated.
     * Automatically updated when the page is modified.
     * Отметка времени, когда страница была последний раз обновлена.
     * Автоматически обновляется при изменении страницы.
     *
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Default constructor for JPA.
     * Initializes collections and default values.
     * Конструктор по умолчанию для JPA.
     * Инициализирует коллекции и значения по умолчанию.
     */
    public Page() {
        this.translations = new ArrayList<>();
        this.isPublished = false;
        this.sortOrder = 0;
    }

    /**
     * Constructor with required fields for creating a new page.
     * Конструктор с обязательными полями для создания новой страницы.
     *
     * @param slug the unique URL slug / уникальный URL-идентификатор
     */
    public Page(String slug) {
        this();
        this.slug = slug;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    // Getters and setters with comprehensive JavaDoc...

    /**
     * Gets the unique identifier of the page.
     * Получает уникальный идентификатор страницы.
     *
     * @return the page ID / идентификатор страницы
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the page.
     * Note: This is typically set automatically by JPA.
     * Устанавливает уникальный идентификатор страницы.
     * Примечание: Обычно устанавливается автоматически JPA.
     *
     * @param id the page ID / идентификатор страницы
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the unique URL slug for the page.
     * Получает уникальный URL-идентификатор для страницы.
     *
     * @return the URL slug / URL-идентификатор
     */
    public String getSlug() {
        return slug;
    }

    /**
     * Sets the unique URL slug for the page.
     * Устанавливает уникальный URL-идентификатор для страницы.
     *
     * @param slug the URL slug / URL-идентификатор
     */
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * Gets the list of translations for this page.
     * Returns an empty list if no translations exist.
     * Получает список переводов для этой страницы.
     * Возвращает пустой список, если переводов не существует.
     *
     * @return list of page translations / список переводов страницы
     */
    public List<PageTranslation> getTranslations() {
        return translations;
    }

    /**
     * Sets the list of translations for this page.
     * Replaces any existing translations.
     * Устанавливает список переводов для этой страницы.
     * Заменяет любые существующие переводы.
     *
     * @param translations list of page translations / список переводов страницы
     */
    public void setTranslations(List<PageTranslation> translations) {
        this.translations = translations;
    }

    /**
     * Adds a translation to this page.
     * Sets the bidirectional relationship.
     * Добавляет перевод к этой странице.
     * Устанавливает двунаправленную связь.
     *
     * @param translation the translation to add / перевод для добавления
     */
    public void addTranslation(PageTranslation translation) {
        translation.setPage(this);
        this.translations.add(translation);
    }

    /**
     * Removes a translation from this page.
     * Clears the bidirectional relationship.
     * Удаляет перевод из этой страницы.
     * Очищает двунаправленную связь.
     *
     * @param translation the translation to remove / перевод для удаления
     */
    public void removeTranslation(PageTranslation translation) {
        this.translations.remove(translation);
        translation.setPage(null);
    }

    /**
     * Gets the publication status of the page.
     * Получает статус публикации страницы.
     *
     * @return true if page is published / true если страница опубликована
     */
    public Boolean getIsPublished() {
        return isPublished;
    }

    /**
     * Sets the publication status of the page.
     * Устанавливает статус публикации страницы.
     *
     * @param isPublished true to publish the page / true для публикации страницы
     */
    public void setIsPublished(Boolean isPublished) {
        this.isPublished = isPublished;
    }

    /**
     * Gets the sort order of the page.
     * Получает порядок сортировки страницы.
     *
     * @return the sort order value / значение порядка сортировки
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the sort order of the page.
     * Устанавливает порядок сортировки страницы.
     *
     * @param sortOrder the sort order value / значение порядка сортировки
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * Gets the creation timestamp.
     * Получает отметку времени создания.
     *
     * @return the creation timestamp / отметка времени создания
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp.
     * Typically called automatically before entity persistence.
     * Устанавливает отметку времени создания.
     * Обычно вызывается автоматически перед сохранением сущности.
     *
     * @param createdAt the creation timestamp / отметка времени создания
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Gets the last update timestamp.
     * Получает отметку времени последнего обновления.
     *
     * @return the update timestamp / отметка времени обновления
     */
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the last update timestamp.
     * Typically called automatically before entity update.
     * Устанавливает отметку времени последнего обновления.
     * Обычно вызывается автоматически перед обновлением сущности.
     *
     * @param updatedAt the update timestamp / отметка времени обновления
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Returns a string representation of the page.
     * Includes ID, slug and publication status for debugging purposes.
     * Возвращает строковое представление страницы.
     * Включает ID, идентификатор и статус публикации для целей отладки.
     *
     * @return string representation of the page / строковое представление страницы
     */
    @Override
    public String toString() {
        return "Page{" +
                "id=" + id +
                ", slug='" + slug + '\'' +
                ", isPublished=" + isPublished +
                '}';
    }
}